"""
Tableau Prep Script: REST/GraphQL API caller.

Generated by tableau-prep-etl skill from templates/api_caller.py.j2.

URL: https://api.data.gov/ed/collegescorecard/v1/schools?api_key=DEMO_KEY&school.degrees_awarded.predominant=2,3&fields=id,school.name,school.state,school.city,school.zip,school.school_url,school.ownership,school.locale,latest.student.size,latest.cost.attendance.academic_year,latest.cost.tuition.in_state,latest.cost.tuition.out_of_state,latest.completion.completion_rate_4yr_150nt,latest.completion.completion_rate_less_than_4yr_150nt,latest.aid.median_debt.completers.overall,latest.earnings.10_yrs_after_entry.median,latest.earnings.6_yrs_after_entry.median,latest.repayment.3_yr_default_rate,latest.admissions.admission_rate.overall
Auth: none
Format hint: json
GraphQL: False

Format dispatch:
  - json (default)            : JSON-decode the response, drill envelope keys
  - csv                       : pd.read_csv() on the response body
  - csv_index_then_zip        : parse HTML directory listing for the latest
                                .CSV.zip, fetch + unzip + read CSV
                                (used by GDELT-style sources)
  - jsonl / ndjson            : line-delimited JSON
  - arcgis_features           : ArcGIS REST FeatureServer/MapServer query
                                endpoint. Walks resultOffset pagination,
                                flattens 'attributes' (+ optional point
                                geometry) into rows.
"""
import csv
import io
import json
import os
import re
import ssl
import time
import zipfile
from urllib import error, request as urlrequest
from urllib.parse import urljoin, urlparse

import pandas as pd

API_URL = "https://api.data.gov/ed/collegescorecard/v1/schools?api_key=DEMO_KEY&school.degrees_awarded.predominant=2,3&fields=id,school.name,school.state,school.city,school.zip,school.school_url,school.ownership,school.locale,latest.student.size,latest.cost.attendance.academic_year,latest.cost.tuition.in_state,latest.cost.tuition.out_of_state,latest.completion.completion_rate_4yr_150nt,latest.completion.completion_rate_less_than_4yr_150nt,latest.aid.median_debt.completers.overall,latest.earnings.10_yrs_after_entry.median,latest.earnings.6_yrs_after_entry.median,latest.repayment.3_yr_default_rate,latest.admissions.admission_rate.overall"
FORMAT = "json"

GRAPHQL = False


VERIFY_SSL = True
TIMEOUT_S = 60
MAX_RETRIES = 3
COUNTRY_FILTER = ""

INDEX_LINK_PATTERN = r'href="([^"]+\.CSV\.zip)"'

# ArcGIS-specific knobs (ignored when format != 'arcgis_features')
ARCGIS_WHERE = "1=1"
ARCGIS_OUT_FIELDS = "*"
ARCGIS_PAGE_SIZE = 1000
ARCGIS_MAX_RECORDS = 0  # 0 = no cap
ARCGIS_RETURN_GEOMETRY = True
ARCGIS_OUT_SR = 4326  # 4326 = WGS84 lat/lon
# 'point' (default) or 'polyline'. Polyline mode flattens first/last
# vertex of the first path into start_lon/start_lat/end_lon/end_lat —
# the canonical edge-table shape for graph analytics on transmission
# lines, road networks, etc.
ARCGIS_GEOMETRY_KIND = "point"
# Optional per-field type overrides for the schema heuristic. Maps
# {field_name: 'string'|'int'|'decimal'}. The default heuristic flags
# only date/time/lat/lon-like names as non-string; numeric fields with
# unrelated names (e.g. VOLTAGE, KVA) need to be declared explicitly
# or Maestro rejects the dataset with "A string type is required for
# field [X]" when the actual rows carry numbers.
ARCGIS_FIELD_TYPES = {}

# CSV-specific knobs (ignored when format != 'csv').
# CSV_ENCODING: e.g. 'utf-8' or 'latin-1'. Some open-data publishers
#   ship Latin-1 CSVs that mojibake-decode under utf-8.
# CSV_RENAME_MAP: rename columns post-read so downstream nodes see clean,
#   join-friendly names (esp. when source uses bilingual `English:French`
#   headers — Maestro accepts them but they're awkward to reference).
# CSV_SCHEMA: explicit {column: prep_type} for get_output_schema(). Required
#   when generate_flow needs to wire joins on specific columns; otherwise
#   stub schema causes "Unable to retrieve results for field" downstream.
# CSV_USECOLS: optional list of source columns to keep (post-rename if
#   present in CSV_RENAME_MAP). Trims wide CSVs.
CSV_ENCODING = "utf-8"
CSV_RENAME_MAP = {}
CSV_SCHEMA = {}
CSV_USECOLS = []

# JSON pagination knobs (ignored when format != 'json' or when
# JSON_PAGINATE is False). Public open-data REST APIs (Treasury Fiscal
# Data, College Scorecard, BTS, etc.) cap a single response below the
# total filtered row count and require the caller to walk pages.
# JSON_PAGINATE: master switch.
# JSON_PAGE_PARAM: query-string key for the page index (e.g. 'page',
#   'page[number]', 'offset'). For JSON:API style nested keys, brackets
#   are URL-encoded automatically.
# JSON_PAGE_SIZE_PARAM: query-string key for page size (or '' if not
#   applicable). PAGE_SIZE is appended only when this is non-empty.
# JSON_PAGE_SIZE: rows per page; cap to whatever the publisher allows.
# JSON_PAGE_START: first page index (1 for most, 0 for offset-style).
# JSON_PAGE_KIND: 'index' (page=1,2,3,...) or 'offset' (offset=0,N,2N,...).
# JSON_MAX_PAGES: hard cap to prevent runaway loops on broken APIs.
JSON_SCHEMA = {"id": "int", "latest.admissions.admission_rate.overall": "decimal", "latest.aid.median_debt.completers.overall": "int", "latest.completion.completion_rate_4yr_150nt": "decimal", "latest.completion.completion_rate_less_than_4yr_150nt": "decimal", "latest.cost.attendance.academic_year": "int", "latest.cost.tuition.in_state": "int", "latest.cost.tuition.out_of_state": "int", "latest.earnings.10_yrs_after_entry.median": "int", "latest.earnings.6_yrs_after_entry.median": "int", "latest.repayment.3_yr_default_rate": "decimal", "latest.student.size": "int", "school.city": "string", "school.locale": "int", "school.name": "string", "school.ownership": "int", "school.school_url": "string", "school.state": "string", "school.zip": "string"}
# JSON HTTP method/body knobs. Many open-data APIs accept POST with a
# JSON body for richer queries (e.g. BLS Public Data API: 'seriesid'
# arrays, GraphQL endpoints emulating REST). For non-GraphQL POSTs
# the body is sent verbatim. JSON_RECORDS_PATH lets the response
# extractor find records under a nested key like 'Results.series.0.data'
# (dotted path; '0' indexes the first list item).
JSON_HTTP_METHOD = "GET"

JSON_BODY = None
JSON_RECORDS_PATH = "results"
# When the records-path resolves to a LIST of parent objects each
# containing an inner list of records (e.g. BLS:
# Results.series=[{seriesID, data=[{year, period, value}, ...]}]),
# JSON_FLATTEN_INNER_KEY names the inner list to expand and
# JSON_FLATTEN_PARENT_KEYS lists which parent fields to copy onto
# each emitted row. Without this, the result is one row per series
# with the per-month data trapped in a list-valued cell.
JSON_FLATTEN_INNER_KEY = ""
JSON_FLATTEN_PARENT_KEYS = []
# Derived columns: post-fetch in-Python column synthesis. Common need:
# build an obs_date from year + period (e.g. BLS M01-M12 -> '2024-01-01').
# Each entry: {"name": "obs_date", "kind": "year_month_iso",
#              "year_col": "year", "period_col": "period"} where
# kind in ('year_month_iso', 'concat'). Add more kinds as new sources
# need them; the goal is to keep one-off Python out of specs.
JSON_DERIVED_COLUMNS = []
JSON_PAGINATE = True
JSON_PAGE_PARAM = "page"
JSON_PAGE_SIZE_PARAM = "per_page"
JSON_PAGE_SIZE = 100
JSON_PAGE_START = 0
JSON_PAGE_KIND = "index"
JSON_MAX_PAGES = 100


def _ssl_ctx():
    try:
        if not VERIFY_SSL:
            return ssl._create_unverified_context()
        # macOS Python.org distros often lack a system CA bundle; prefer
        # certifi's bundle when available so HTTPS to public APIs works
        # out-of-the-box under TabPy without requiring the user to run
        # /Applications/Python*/Install\ Certificates.command first.
        try:
            import certifi
            return ssl.create_default_context(cafile=certifi.where())
        except ImportError:
            return ssl.create_default_context()
    except Exception:
        return None


def _build_headers():
    headers = {"Content-Type": "application/json"}
    
    return headers


def _http_get_bytes(url: str) -> bytes:
    headers = _build_headers()
    ctx = _ssl_ctx()
    attempt = 0
    while True:
        req = urlrequest.Request(url, method="GET")
        for k, v in headers.items():
            req.add_header(k, v)
        try:
            with urlrequest.urlopen(req, timeout=TIMEOUT_S, context=ctx) as resp:
                return resp.read()
        except error.HTTPError as e:
            # 4xx (other than 429 rate-limit) is permanent — re-raise
            # immediately so the caller can decide (e.g. paginated
            # walk treats 4xx mid-walk as end-of-data when rows exist).
            if e.code != 429 and 400 <= e.code < 500:
                raise
            if attempt < MAX_RETRIES:
                attempt += 1
                time.sleep(2 ** attempt)
                continue
            raise
        except (error.URLError, TimeoutError):
            if attempt < MAX_RETRIES:
                attempt += 1
                time.sleep(2 ** attempt)
                continue
            raise


def _http_request_json(payload=None, method="GET"):
    body = json.dumps(payload).encode("utf-8") if payload else None
    headers = _build_headers()
    ctx = _ssl_ctx()
    attempt = 0
    while True:
        req = urlrequest.Request(API_URL, data=body, method=method)
        for k, v in headers.items():
            req.add_header(k, v)
        try:
            with urlrequest.urlopen(req, timeout=TIMEOUT_S, context=ctx) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except (error.HTTPError, error.URLError, TimeoutError):
            if attempt < MAX_RETRIES:
                attempt += 1
                time.sleep(2 ** attempt)
                continue
            raise


def _df_from_csv_bytes(b: bytes, has_header: bool = True) -> pd.DataFrame:
    # GDELT (csv_index_then_zip) is always UTF-8; OTF concordance files are
    # Latin-1. Honor CSV_ENCODING for the headered-CSV path.
    encoding = CSV_ENCODING if has_header else "utf-8"
    text = b.decode(encoding, errors="replace")
    if has_header:
        # Honor CSV_SCHEMA's declared 'string' columns at read time so
        # pandas doesn't silently coerce leading-zero values (account
        # numbers, routing numbers, ZIP codes, IDs, SSN-like strings)
        # to int/float. If we let pandas auto-detect, '000234567890'
        # becomes 234567890.0, the get_output_schema then declares the
        # column as prep_string(), and Maestro rejects with "A string
        # type is required for field [X]". Apply post-rename so the
        # dtype map keys match what users wrote in CSV_SCHEMA.
        post_rename_strings = {
            c for c, t in CSV_SCHEMA.items()
            if (t or "").lower() == "string"
        }
        rename_inverse = {v: k for k, v in (CSV_RENAME_MAP or {}).items()}
        pre_rename_strings = {
            rename_inverse.get(c, c) for c in post_rename_strings
        }
        df = pd.read_csv(
            io.StringIO(text),
            dtype={c: str for c in pre_rename_strings} or None,
            keep_default_na=False,
            na_values=[""],
        )
        if CSV_RENAME_MAP:
            df = df.rename(columns=CSV_RENAME_MAP)
        if CSV_USECOLS:
            keep = [c for c in CSV_USECOLS if c in df.columns]
            df = df[keep]
        # Belt-and-suspenders: any column declared 'string' that still
        # came back numeric (e.g. when CSV_SCHEMA wasn't supplied for it
        # but get_output_schema defaults to string) gets coerced now.
        for col, t in CSV_SCHEMA.items():
            if (t or "").lower() == "string" and col in df.columns:
                df[col] = df[col].astype(str).where(df[col].notna(), "")
        return df
    # GDELT events don't ship a header; use the v1 column list
    GDELT_V1_COLS = [
        "GLOBALEVENTID", "SQLDATE", "MonthYear", "Year", "FractionDate",
        "Actor1Code", "Actor1Name", "Actor1CountryCode", "Actor1KnownGroupCode",
        "Actor1EthnicCode", "Actor1Religion1Code", "Actor1Religion2Code",
        "Actor1Type1Code", "Actor1Type2Code", "Actor1Type3Code",
        "Actor2Code", "Actor2Name", "Actor2CountryCode", "Actor2KnownGroupCode",
        "Actor2EthnicCode", "Actor2Religion1Code", "Actor2Religion2Code",
        "Actor2Type1Code", "Actor2Type2Code", "Actor2Type3Code",
        "IsRootEvent", "EventCode", "EventBaseCode", "EventRootCode",
        "QuadClass", "GoldsteinScale", "NumMentions", "NumSources",
        "NumArticles", "AvgTone", "Actor1Geo_Type", "Actor1Geo_FullName",
        "Actor1Geo_CountryCode", "Actor1Geo_ADM1Code", "Actor1Geo_Lat",
        "Actor1Geo_Long", "Actor1Geo_FeatureID",
        "Actor2Geo_Type", "Actor2Geo_FullName", "Actor2Geo_CountryCode",
        "Actor2Geo_ADM1Code", "Actor2Geo_Lat", "Actor2Geo_Long", "Actor2Geo_FeatureID",
        "ActionGeo_Type", "ActionGeo_FullName", "ActionGeo_CountryCode",
        "ActionGeo_ADM1Code", "ActionGeo_Lat", "ActionGeo_Long", "ActionGeo_FeatureID",
        "DATEADDED", "SOURCEURL",
    ]
    return pd.read_csv(io.StringIO(text), sep="\t", header=None, names=GDELT_V1_COLS,
                       low_memory=False)


def _fetch_csv_index_then_zip() -> pd.DataFrame:
    """Format: csv_index_then_zip.
    Read API_URL as an HTML directory listing, find the latest .CSV.zip
    link, fetch + unzip + read the CSV. Tailored to GDELT events index."""
    index_html = _http_get_bytes(API_URL).decode("utf-8", errors="replace")
    matches = re.findall(INDEX_LINK_PATTERN, index_html, flags=re.IGNORECASE)
    if not matches:
        raise RuntimeError(f"no .CSV.zip links matched at {API_URL}")
    # Pick the most recent (lexicographic max for date-prefixed filenames)
    latest = sorted(matches)[-1]
    # Resolve relative to the index URL's directory
    base = API_URL.rsplit("/", 1)[0] + "/"
    zip_url = urljoin(base, latest)
    zip_bytes = _http_get_bytes(zip_url)
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
        csv_names = [n for n in zf.namelist() if n.lower().endswith(".csv")]
        if not csv_names:
            raise RuntimeError(f"no CSV inside {zip_url}")
        with zf.open(csv_names[0]) as fp:
            csv_bytes = fp.read()
    df = _df_from_csv_bytes(csv_bytes, has_header=False)
    if COUNTRY_FILTER and "ActionGeo_CountryCode" in df.columns:
        df = df[df["ActionGeo_CountryCode"] == COUNTRY_FILTER].reset_index(drop=True)
    return df


def _fetch_csv() -> pd.DataFrame:
    return _df_from_csv_bytes(_http_get_bytes(API_URL), has_header=True)


def _fetch_jsonl() -> pd.DataFrame:
    body = _http_get_bytes(API_URL).decode("utf-8", errors="replace")
    rows = [json.loads(ln) for ln in body.splitlines() if ln.strip()]
    return pd.DataFrame(rows)


def _fetch_json() -> pd.DataFrame:
    if GRAPHQL:
        data = _http_request_json({"query": GRAPHQL_QUERY}, method="POST")
        rows = data.get("data") or data
        rows = _unwrap_json_records(rows)
        df = pd.DataFrame(rows) if isinstance(rows, list) else pd.DataFrame([{"raw": json.dumps(rows)}])
        return _apply_json_schema_coercion(df)

    if not JSON_PAGINATE:
        if JSON_HTTP_METHOD.upper() == "POST" and JSON_BODY is not None:
            doc = _http_request_json(JSON_BODY, method="POST")
        else:
            doc = _http_request_json(method="GET")
        rows = _extract_json_records(doc)
        rows = _flatten_inner_records(rows)
        df = pd.DataFrame(rows) if isinstance(rows, list) else pd.DataFrame([{"raw": json.dumps(rows)}])
        return _apply_json_schema_coercion(df)

    # Paginated walk. Treasury Fiscal Data + JSON:API style: append
    # `page[number]=N` (and optionally `page[size]=N`) to API_URL and
    # advance until total-pages reached, an empty page, or MAX_PAGES.
    from urllib.parse import urlencode
    all_rows: list = []
    page = JSON_PAGE_START
    seen_pages = 0
    sep_first = "?" if "?" not in API_URL else "&"
    while seen_pages < JSON_MAX_PAGES:
        if JSON_PAGE_KIND == "offset":
            page_qs = {JSON_PAGE_PARAM: (page - JSON_PAGE_START) * JSON_PAGE_SIZE}
        else:
            page_qs = {JSON_PAGE_PARAM: page}
        if JSON_PAGE_SIZE_PARAM:
            page_qs[JSON_PAGE_SIZE_PARAM] = JSON_PAGE_SIZE
        url = API_URL + sep_first + urlencode(page_qs)
        sep_first = "&"  # subsequent pages always use '&'
        try:
            body = _http_get_bytes(url)
        except error.HTTPError as e:
            # Some publishers return 400 once an offset goes past the
            # advertised total (CMS Provider Data is one). Treat any
            # 4xx mid-walk as "done" if we already collected rows;
            # otherwise re-raise so the user sees the real error.
            if 400 <= getattr(e, "code", 500) < 500 and all_rows:
                break
            raise
        try:
            doc = json.loads(body)
        except Exception:
            break
        rows = _extract_json_records(doc)
        rows = _flatten_inner_records(rows) if isinstance(rows, list) else rows
        if not isinstance(rows, list) or not rows:
            break
        all_rows.extend(rows)
        seen_pages += 1
        # JSON:API style total-pages from meta.
        meta = doc.get("meta") if isinstance(doc, dict) else None
        if isinstance(meta, dict):
            tp = meta.get("total-pages") or meta.get("totalPages")
            if isinstance(tp, int) and page >= tp:
                break
        if len(rows) < JSON_PAGE_SIZE:
            break  # underfilled page = last page
        page += 1
    df = pd.DataFrame(all_rows) if all_rows else pd.DataFrame()
    return _apply_json_schema_coercion(df)


def _unwrap_json_records(rows):
    """Generic record-extractor: if a JSON response is wrapped in a
    common envelope key, return the inner list; otherwise pass through."""
    if isinstance(rows, dict):
        for key in ("results", "data", "items", "records", "rows"):
            if key in rows and isinstance(rows[key], list):
                return rows[key]
    return rows


def _flatten_inner_records(rows):
    """When JSON_FLATTEN_INNER_KEY is set, expand each parent record's
    inner list into one row per inner item, copying named parent
    fields onto every row. Used for response shapes like BLS where
    one parent (`series`) holds a list of monthly observations."""
    if not JSON_FLATTEN_INNER_KEY or not isinstance(rows, list):
        return rows
    out: list = []
    for parent in rows:
        if not isinstance(parent, dict):
            continue
        inner = parent.get(JSON_FLATTEN_INNER_KEY) or []
        if not isinstance(inner, list):
            continue
        carry = {k: parent.get(k) for k in JSON_FLATTEN_PARENT_KEYS if k in parent}
        for item in inner:
            if isinstance(item, dict):
                row = dict(carry)
                row.update(item)
                out.append(row)
    return out


def _extract_json_records(doc):
    """Resolve a JSON response to a list of record dicts. When
    JSON_RECORDS_PATH is set, walk the dotted path (numeric segments
    index into lists). Otherwise fall back to _unwrap_json_records.
    Used to pull a specific list out of nested envelopes that don't
    fit the standard 'results'/'data'/'items'/'records'/'rows' keys
    (e.g. BLS: 'Results.series.0.data')."""
    if not JSON_RECORDS_PATH:
        return _unwrap_json_records(doc)
    cur = doc
    for seg in JSON_RECORDS_PATH.split("."):
        if isinstance(cur, list):
            try:
                cur = cur[int(seg)]
            except (ValueError, IndexError):
                return cur
        elif isinstance(cur, dict):
            cur = cur.get(seg)
        else:
            return cur
        if cur is None:
            return []
    return cur


def _apply_json_schema_coercion(df: pd.DataFrame) -> pd.DataFrame:
    """Apply JSON_SCHEMA-driven type coercion to the raw fetched
    dataframe. JSON over the wire is all strings (or mixed strings +
    numbers + nulls); some publishers (e.g. Treasury Fiscal Data)
    serialize SQL NULLs as the literal string 'null', which pandas
    leaves in place as object dtype. Without this normalization,
    decimal/int columns reach Maestro as object and trigger
    'A decimal type is required for field [X]' rejections."""
    if df is None or len(df) == 0 or not JSON_SCHEMA:
        return df
    # 1) Sentinel nulls: lowercase 'null', empty string -> NaN. Done
    #    once across all object cols so downstream coercions see real NaN.
    sentinels = {"null", "Null", "NULL", "None", ""}
    obj_cols = [c for c in df.columns if df[c].dtype == "object"]
    for c in obj_cols:
        df[c] = df[c].where(~df[c].isin(sentinels), None)
    # 2) Synthesize derived columns from JSON_DERIVED_COLUMNS specs.
    #    Run BEFORE the column-keep trim so derived names are eligible.
    for derived in JSON_DERIVED_COLUMNS:
        try:
            name = derived.get("name")
            kind = derived.get("kind", "")
            if not name or kind == "":
                continue
            if kind == "year_month_iso":
                year_col = derived.get("year_col", "year")
                period_col = derived.get("period_col", "period")
                if year_col in df.columns and period_col in df.columns:
                    def _ym(yr, pr):
                        try:
                            yi = int(yr)
                            ps = str(pr or "")
                            if ps.startswith("M"):
                                m = int(ps[1:])
                            elif ps.startswith("Q"):
                                m = (int(ps[1:]) - 1) * 3 + 1
                            else:
                                m = int(ps)
                            if 1 <= m <= 12:
                                return f"{yi:04d}-{m:02d}-01"
                        except (TypeError, ValueError):
                            pass
                        return ""
                    df[name] = [_ym(y, p) for y, p in zip(df[year_col], df[period_col])]
            elif kind == "concat":
                cols = derived.get("cols", [])
                sep = derived.get("sep", "")
                if all(c in df.columns for c in cols):
                    df[name] = df[cols].astype(str).agg(sep.join, axis=1)
            elif kind == "list_join":
                # Flatten a list-valued column into a delimited string.
                # Useful for JSON sources that emit ['CWE-306', 'CWE-22']
                # — Maestro doesn't accept list-typed wire values.
                src_col = derived.get("source_col")
                sep = derived.get("sep", ", ")
                if src_col and src_col in df.columns:
                    df[name] = df[src_col].apply(
                        lambda v: sep.join(str(x) for x in v) if isinstance(v, list) else (str(v) if v is not None else "")
                    )
            elif kind == "list_first_field":
                # Pull a named field out of the first dict in a list-
                # valued column. Common need: APIs return
                # `agencies: [{name: 'X', ...}, ...]` — Tableau wants
                # a flat string. When the list is empty or non-dict,
                # fall back to empty string.
                src_col = derived.get("source_col")
                field = derived.get("field", "name")
                if src_col and src_col in df.columns:
                    def _first(v):
                        if isinstance(v, list) and v:
                            head = v[0]
                            if isinstance(head, dict):
                                return str(head.get(field, "") or "")
                        return ""
                    df[name] = df[src_col].apply(_first)
            elif kind == "days_since":
                # Calendar days from an ISO-date string column to today
                # (UTC). Useful for "days_since_filed", "days_open",
                # etc. in case-management style flows.
                src_col = derived.get("source_col")
                if src_col and src_col in df.columns:
                    s = pd.to_datetime(df[src_col], errors="coerce", utc=True)
                    now = pd.Timestamp.now(tz="UTC").normalize()
                    df[name] = (now - s).dt.days.fillna(0).astype("int64")
            elif kind == "days_between":
                # Calendar days between two ISO-date string columns.
                # Negative when the earlier column is later (rare in
                # SLA-style "added vs due" pairs).
                start_col = derived.get("start_col")
                end_col = derived.get("end_col")
                if start_col in df.columns and end_col in df.columns:
                    s = pd.to_datetime(df[start_col], errors="coerce")
                    e = pd.to_datetime(df[end_col], errors="coerce")
                    df[name] = (e - s).dt.days.fillna(0).astype("int64")
        except Exception:
            continue
    # 3) Drop any columns the publisher returned that aren't in the
    #    declared schema. Maestro's compile-time inspector matches the
    #    fetcher's actual output to get_output_schema(); extras are
    #    silently filtered upstream of downstream nodes, which can
    #    leave them empty if Maestro's schema-projection pass loses
    #    rows. Easier to align here.
    keep = list(JSON_SCHEMA.keys())
    df = df[[c for c in keep if c in df.columns]].copy()
    # 3) Apply per-column declared type from JSON_SCHEMA.
    for col, decl in JSON_SCHEMA.items():
        if col not in df.columns:
            continue
        d = (decl or "").lower()
        try:
            s = df[col]
            if d == "int":
                df[col] = pd.to_numeric(s, errors="coerce").fillna(0).astype("int64")
            elif d in ("decimal", "float", "double"):
                df[col] = pd.to_numeric(s, errors="coerce")
            elif d == "bool":
                df[col] = s.astype("bool")
            elif d in ("date", "datetime"):
                # Keep ISO 8601 string per the Maestro rule (Prep accepts
                # ISO strings under prep_date/prep_datetime). Don't
                # round-trip via pd.to_datetime; that creates Timestamp
                # objects which then mis-serialize through TabPy.
                df[col] = s.fillna("").astype(str)
            else:  # 'string' or unknown
                df[col] = s.fillna("").astype(str)
        except Exception:
            continue
    return df


def _fetch_arcgis_features() -> pd.DataFrame:
    """Format: arcgis_features.
    Query an ArcGIS REST FeatureServer/MapServer layer's /query endpoint,
    walk resultOffset pagination, flatten attributes + point geometry."""
    from urllib.parse import urlencode

    base = API_URL.rstrip("/")
    if not base.endswith("/query"):
        base = base + "/query"

    rows: list[dict] = []
    offset = 0
    while True:
        params = {
            "where": ARCGIS_WHERE,
            "outFields": ARCGIS_OUT_FIELDS,
            "f": "json",
            "returnGeometry": "true" if ARCGIS_RETURN_GEOMETRY else "false",
            "outSR": str(ARCGIS_OUT_SR),
            "resultOffset": str(offset),
            "resultRecordCount": str(ARCGIS_PAGE_SIZE),
        }
        url = base + "?" + urlencode(params)
        body = _http_get_bytes(url)
        data = json.loads(body.decode("utf-8", errors="replace"))
        if "error" in data:
            raise RuntimeError(f"ArcGIS error: {data['error']}")
        feats = data.get("features") or []
        if not feats:
            break
        for f in feats:
            attrs = dict(f.get("attributes") or {})
            geom = f.get("geometry") or {}
            # Point geometry: flatten x/y to lon/lat
            if "x" in geom and "y" in geom:
                attrs.setdefault("longitude", geom.get("x"))
                attrs.setdefault("latitude", geom.get("y"))
            # Polyline geometry: extract first and last vertex of the
            # first path as start/end endpoints. Sufficient for graph
            # edge tables where each line connects two stations.
            elif "paths" in geom and geom["paths"]:
                first_path = geom["paths"][0]
                if first_path:
                    sx, sy = first_path[0][0], first_path[0][1]
                    ex, ey = first_path[-1][0], first_path[-1][1]
                    attrs.setdefault("start_lon", sx)
                    attrs.setdefault("start_lat", sy)
                    attrs.setdefault("end_lon", ex)
                    attrs.setdefault("end_lat", ey)
            elif geom:
                attrs.setdefault("geometry_json", json.dumps(geom))
            rows.append(attrs)
        if ARCGIS_MAX_RECORDS and len(rows) >= ARCGIS_MAX_RECORDS:
            rows = rows[:ARCGIS_MAX_RECORDS]
            break
        # ArcGIS sets exceededTransferLimit when more pages remain
        if not data.get("exceededTransferLimit") and len(feats) < ARCGIS_PAGE_SIZE:
            break
        offset += len(feats)

    df = pd.DataFrame(rows)
    # ArcGIS epoch-millis timestamp fields → ISO 8601 strings.
    # We emit strings (not pd.Timestamp) because TabPy serializes the
    # response via json.dumps which can't handle Timestamp objects;
    # Tableau Prep + the script's `prep_string()` declaration both
    # happily accept the ISO string. The column MUST end up as pure
    # str dtype (not pandas object containing mixed Timestamp/None) -
    # Maestro 2026.1 inspects the wire dtype on the way in and rejects
    # the run with "A string type is required for [X]" if the column
    # is anything but a clean string series.
    # An explicit type override always wins over the name heuristic.
    # Without this, names like `ActiveFireCandidate` end with the
    # substring "date" and get coerced to ISO strings even when the
    # source already declares them as int.
    explicit = ARCGIS_FIELD_TYPES if FORMAT == "arcgis_features" else {}
    for col in df.columns:
        if col in explicit:
            continue
        lf = col.lower()
        # CamelCase columns like `FireDiscoveryDateTime` end in 'datetime',
        # but `ActiveFireCandidate` also ends in 'date' (substring of
        # 'Candidate'). Require an underscore boundary OR an exact
        # CamelCase tail (preceding char lowercase).
        is_date_col = False
        for suf in ("datetime", "date", "time", "_dt"):
            if lf.endswith(suf):
                if suf.startswith("_"):  # _dt
                    is_date_col = True
                    break
                # Boundary check: must be preceded by '_' or a
                # lowercase->uppercase camelcase transition.
                idx = len(lf) - len(suf)
                if idx == 0:
                    is_date_col = True
                    break
                prev_lower = lf[idx - 1]
                if prev_lower == "_":
                    is_date_col = True
                    break
                # CamelCase: preceding char in ORIGINAL was uppercase
                # break (e.g. `DiscoveryDate` - 'D' starts the suffix).
                # We approximate: require the original-case char at
                # position idx to be uppercase. Without this,
                # `Candidate` would still slip through.
                if idx < len(col) and col[idx].isupper():
                    is_date_col = True
                    break
        if not is_date_col:
            continue
        try:
            ts = pd.to_datetime(df[col], unit="ms", errors="coerce", utc=True)
            iso = ts.dt.strftime("%Y-%m-%dT%H:%M:%SZ")
            df[col] = iso.where(ts.notna(), "").astype(str)
        except Exception:
            try:
                df[col] = df[col].fillna("").astype(str)
            except Exception:
                pass
    return df


_DISPATCH = {
    "json": _fetch_json,
    "csv": _fetch_csv,
    "csv_index_then_zip": _fetch_csv_index_then_zip,
    "jsonl": _fetch_jsonl,
    "ndjson": _fetch_jsonl,
    "arcgis_features": _fetch_arcgis_features,
}


def call_api(df):
    """Tableau Prep entry point. Input df is a trigger row (single 'folder'-like
    column from the rewired local xlsx). We ignore it and pull from the API.
    Output: a DataFrame matching the API's records, schema-inferred.

    Coerces every output column into the dtype declared by
    `get_output_schema()`. Tableau Prep is strict: a column declared
    `prep_int()` whose actual values are floats / pandas objects /
    NaN-mixed-with-ints is rejected with "An integer type is required
    for field [X]". This applies to every fetcher branch."""
    fetcher = _DISPATCH.get(FORMAT, _fetch_json)
    out_df = fetcher()
    return _coerce_to_declared_schema(out_df)


def _coerce_to_declared_schema(df):
    """Cast each column of `df` to match what `get_output_schema()`
    declares. Maestro's compile-time schema check rejects columns
    whose actual dtype doesn't match the helper used in the schema
    (e.g. prep_int with object dtype, prep_string with datetime64).

    Without this final pass, ArcGIS' SmallInteger fields (which arrive
    as pandas float64 because they may be NaN) get declared as
    prep_int but rejected by Maestro. Same family of failure for date
    cols that round-tripped via pd.to_datetime."""
    if df is None or len(df) == 0:
        return df
    try:
        schema_df = get_output_schema()
        declared = {col: schema_df[col].iloc[0] if len(schema_df) > 0 else None
                    for col in schema_df.columns}
    except Exception:
        return df
    int_marker = type(prep_int()) if hasattr(__builtins__, "prep_int") or "prep_int" in dir() else None  # noqa: F821
    # Use the actual function references for type checks.
    INT_TY = prep_int()       # noqa: F821
    DEC_TY = prep_decimal()   # noqa: F821
    BOOL_TY = prep_bool()     # noqa: F821
    STR_TY = prep_string()    # noqa: F821
    try:
        DATE_TY = prep_date()      # noqa: F821
        DT_TY   = prep_datetime()  # noqa: F821
    except Exception:
        DATE_TY = None
        DT_TY = None

    def _is(ty, ref):
        return ref is not None and type(ty).__name__ == type(ref).__name__

    for col, ty in declared.items():
        if col not in df.columns:
            continue
        try:
            s = df[col]
            if _is(ty, INT_TY):
                # ints must be Python ints (not float). Replace NaN with 0
                # since Maestro's int wire format has no null marker on
                # this path; analysts can filter on 0 if they need to.
                df[col] = pd.to_numeric(s, errors="coerce").fillna(0).astype("int64")
            elif _is(ty, DEC_TY):
                df[col] = pd.to_numeric(s, errors="coerce")
            elif _is(ty, BOOL_TY):
                df[col] = s.astype("bool")
            elif _is(ty, STR_TY):
                df[col] = s.fillna("").astype(str) if hasattr(s, "fillna") else s.astype(str)
            # date / datetime declared columns: leave string ISO 8601 as-is
            # (Tableau accepts ISO strings under prep_date/prep_datetime).
        except Exception:
            # Don't fail the whole fetch over one column; let Maestro
            # surface the error so the user can correct the spec.
            continue
    return df


_GDELT_V1_DECIMAL = {
    "FractionDate", "GoldsteinScale", "AvgTone",
    "Actor1Geo_Lat", "Actor1Geo_Long",
    "Actor2Geo_Lat", "Actor2Geo_Long",
    "ActionGeo_Lat", "ActionGeo_Long",
}
_GDELT_V1_INT = {
    "GLOBALEVENTID", "SQLDATE", "MonthYear", "Year", "IsRootEvent",
    "EventCode", "EventBaseCode", "EventRootCode", "QuadClass",
    "NumMentions", "NumSources", "NumArticles", "DATEADDED",
    "Actor1Geo_Type", "Actor2Geo_Type", "ActionGeo_Type",
}


def _gdelt_v1_schema():
    GDELT_V1_COLS = [
        "GLOBALEVENTID", "SQLDATE", "MonthYear", "Year", "FractionDate",
        "Actor1Code", "Actor1Name", "Actor1CountryCode", "Actor1KnownGroupCode",
        "Actor1EthnicCode", "Actor1Religion1Code", "Actor1Religion2Code",
        "Actor1Type1Code", "Actor1Type2Code", "Actor1Type3Code",
        "Actor2Code", "Actor2Name", "Actor2CountryCode", "Actor2KnownGroupCode",
        "Actor2EthnicCode", "Actor2Religion1Code", "Actor2Religion2Code",
        "Actor2Type1Code", "Actor2Type2Code", "Actor2Type3Code",
        "IsRootEvent", "EventCode", "EventBaseCode", "EventRootCode",
        "QuadClass", "GoldsteinScale", "NumMentions", "NumSources",
        "NumArticles", "AvgTone", "Actor1Geo_Type", "Actor1Geo_FullName",
        "Actor1Geo_CountryCode", "Actor1Geo_ADM1Code", "Actor1Geo_Lat",
        "Actor1Geo_Long", "Actor1Geo_FeatureID",
        "Actor2Geo_Type", "Actor2Geo_FullName", "Actor2Geo_CountryCode",
        "Actor2Geo_ADM1Code", "Actor2Geo_Lat", "Actor2Geo_Long", "Actor2Geo_FeatureID",
        "ActionGeo_Type", "ActionGeo_FullName", "ActionGeo_CountryCode",
        "ActionGeo_ADM1Code", "ActionGeo_Lat", "ActionGeo_Long", "ActionGeo_FeatureID",
        "DATEADDED", "SOURCEURL",
    ]
    schema = {}
    for c in GDELT_V1_COLS:
        if c in _GDELT_V1_INT:
            schema[c] = prep_int()  # noqa: F821
        elif c in _GDELT_V1_DECIMAL:
            schema[c] = prep_decimal()  # noqa: F821
        else:
            schema[c] = prep_string()  # noqa: F821
    return schema


def get_output_schema():
    # Schema must match what call_api actually returns or Maestro fails with
    # "Unable to retrieve results for field". We derive shape from FORMAT
    # because each fetcher returns a different DataFrame shape.
    if FORMAT == "arcgis_features" and ARCGIS_OUT_FIELDS and ARCGIS_OUT_FIELDS != "*":
        fields = [f.strip() for f in ARCGIS_OUT_FIELDS.split(",") if f.strip()]
        type_helpers = {
            "string": prep_string(),      # noqa: F821
            "int": prep_int(),            # noqa: F821
            "decimal": prep_decimal(),    # noqa: F821
            "date": prep_date(),          # noqa: F821
            "datetime": prep_datetime(),  # noqa: F821
            "bool": prep_bool(),          # noqa: F821
        }
        schema = {}
        for f in fields:
            override = ARCGIS_FIELD_TYPES.get(f)
            if override and override in type_helpers:
                schema[f] = type_helpers[override]
                continue
            lf = f.lower()
            # ArcGIS date fields come over the wire as ms-since-epoch
            # ints; api_caller converts them to ISO 8601 strings via
            # `_arcgis_to_iso8601`. We declare them as `prep_string()`
            # here. The Tableau docs claim `prep_datetime()` accepts
            # an ISO 8601 string for that column, but Maestro 2026.1
            # rejects the run with "A datetime type is required for
            # field [X]" when the actual value is the ISO string the
            # docs prescribe. Sticking to string + a downstream
            # ChangeColumnType cast is the only shape that compiles.
            # Word-boundary date/time detection (mirror _fetch_arcgis_features).
            # Names ending in "date" alone (e.g. ActiveFireCandidate)
            # must NOT be treated as date columns.
            is_date_col = False
            for suf in ("datetime", "date", "time", "_dt"):
                if not lf.endswith(suf): continue
                if suf.startswith("_"):
                    is_date_col = True; break
                idx = len(lf) - len(suf)
                if idx == 0:
                    is_date_col = True; break
                if lf[idx - 1] == "_":
                    is_date_col = True; break
                if idx < len(f) and f[idx].isupper():
                    is_date_col = True; break
            if is_date_col:
                schema[f] = prep_string()  # noqa: F821 - emitted as ISO 8601
            elif any(k in lf for k in ("acres", "size", "percent", "lat", "lon")):
                schema[f] = prep_decimal()  # noqa: F821
            elif lf in ("objectid",):
                schema[f] = prep_int()  # noqa: F821
            else:
                schema[f] = prep_string()  # noqa: F821
        if ARCGIS_RETURN_GEOMETRY:
            if ARCGIS_GEOMETRY_KIND == "polyline":
                schema.setdefault("start_lon", prep_decimal())  # noqa: F821
                schema.setdefault("start_lat", prep_decimal())  # noqa: F821
                schema.setdefault("end_lon", prep_decimal())    # noqa: F821
                schema.setdefault("end_lat", prep_decimal())    # noqa: F821
            else:
                schema.setdefault("longitude", prep_decimal())  # noqa: F821
                schema.setdefault("latitude", prep_decimal())   # noqa: F821
        return pd.DataFrame(schema)
    if FORMAT == "csv_index_then_zip":
        return pd.DataFrame(_gdelt_v1_schema())
    if FORMAT in ("json", "jsonl", "ndjson") and JSON_SCHEMA:
        type_map = {
            "string": prep_string(),  # noqa: F821
            "int": prep_int(),  # noqa: F821
            "decimal": prep_decimal(),  # noqa: F821
            "date": prep_date(),  # noqa: F821
            "datetime": prep_datetime(),  # noqa: F821
            "bool": prep_bool(),  # noqa: F821
        }
        schema = {col: type_map.get(t, prep_string()) for col, t in JSON_SCHEMA.items()}  # noqa: F821
        return pd.DataFrame(schema)
    if FORMAT == "csv" and CSV_SCHEMA:
        # Map declared types ('string'|'int'|'decimal'|'date') to Prep helpers.
        type_map = {
            "string": prep_string(),  # noqa: F821
            "int": prep_int(),  # noqa: F821
            "decimal": prep_decimal(),  # noqa: F821
            "date": prep_date(),  # noqa: F821
            "datetime": prep_datetime(),  # noqa: F821
            "bool": prep_bool(),  # noqa: F821
        }
        schema = {col: type_map.get(t, prep_string()) for col, t in CSV_SCHEMA.items()}  # noqa: F821
        return pd.DataFrame(schema)
    return pd.DataFrame({"raw": prep_string()})  # noqa: F821