"""
Phase 11: Metadata writer.

For each `published_data_source` output of a successful publish,
generate (and optionally apply) catalog-style descriptions:

  - DS-level description via REST PUT /api/{ver}/sites/{site}/datasources/{luid}
    (TSC handles this via `server.datasources.update(item)`).
  - Per-column descriptions via .tds XML injection + Overwrite re-publish.
    Tableau Cloud's Metadata API is read-only (verified 2026-06-18
    against usfederaldemos: the GraphQL Mutation root is empty,
    `updateField` / `updateColumn` always return generic "Internal
    Server Error(s) while executing query"). The only supported write
    surface for column descriptions on Cloud is round-tripping the
    .tdsx: `datasources.download` -> unzip -> inject `<column><desc>`
    elements per field into the .tds -> repack -> `datasources.publish
    (mode="Overwrite")`. The same LUID is preserved across the
    overwrite, so callers' references stay valid. This path also
    works on Tableau Server.

Default behavior: AUTO-APPLY. The proposal JSON is always saved to
runtime/<run_id>/metadata_<output_name>.json so there's an audit trail
of what got pushed to the site.

`review=True` writes the proposal and stops without applying. The
orchestrator surfaces it to the user via AskUserQuestion; the user
re-runs without `--review-metadata` once they've approved.

Public surface:
    generate_descriptions(spec, output_name, sample_rows) -> dict
    apply_descriptions(luid, descriptions) -> dict
    write_for_output(spec, output_name, luid, sample_rows, run_dir, *,
                      review=False) -> dict

CLI:
    python3 -m skill.scripts.metadata_writer \\
        --spec runtime/specs/<flow>.json \\
        --output-name <output_name> --columns "col_a,col_b,col_c" \\
        --review --run-dir /tmp/<run>
"""
from __future__ import annotations

import json
import os
import re
import ssl
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional
from urllib import error, request as urlrequest

# Bootstrap tflb_lib + auto_refine import path
from skill.scripts.lib import _REPO_ROOT  # noqa: F401

from skill.scripts.intake import Spec, Output
from skill.scripts.llm_config import load_llm_config


_LLM_CFG = load_llm_config(prompt_if_missing=False)
GATEWAY_URL = _LLM_CFG.url if _LLM_CFG else os.environ.get("LLM_GATEWAY_URL", "")
GATEWAY_KEY = _LLM_CFG.key if _LLM_CFG else os.environ.get("LLM_GATEWAY_KEY", "")
GATEWAY_MODEL = _LLM_CFG.model if _LLM_CFG else os.environ.get(
    "LLM_GATEWAY_MODEL", "claude-sonnet-4-6")
GATEWAY_VERIFY_SSL = False


SYSTEM_PROMPT = """You are a Tableau Server data catalog writer.

Given:
  - A flow's high-level intent (one or two sentences).
  - The name and intended use of one published data source it produces.
  - A list of column names and a few sample rows.

Produce a strict JSON object describing the data, NOT the build process.
Catalog readers want to know what the data IS and what it's GOOD FOR -
they do not care which Python script ran or which Prep nodes fired.

Return ONLY a JSON object with this exact shape:

{
  "ds_description": "<2-4 sentences describing what the data is and what
    business questions it answers. Tense: present (`Contains`,
    `Reports`, `Tracks`). Mention granularity (one row per X) and
    the date range or recency. Avoid: `This flow ...`, `Prep ...`,
    `Generated by ...`.>",
  "columns": [
    {
      "name": "<exact column name from the input list>",
      "description": "<1 sentence. Mention units / format / domain
        (e.g. `ISO 8601 date`, `USD`, `count of cases per month`)
        when sample rows make it obvious. Otherwise describe what
        the column represents. Avoid: column-name restatements
        (`The product_id is the product ID`).>"
    }
  ]
}

Rules:
- Write descriptions a business analyst would value. NEVER mention the
  flow, Prep, scripts, branches, or upstream pipelines.
- One sentence per column. Concise.
- Match `columns[*].name` exactly to the column list provided.
- DO NOT include explanation, markdown fences, or any text outside the JSON.
"""


@dataclass
class DescriptionProposal:
    output_name: str
    luid: str
    ds_description: str = ""
    column_descriptions: dict[str, str] = field(default_factory=dict)
    columns: list[str] = field(default_factory=list)
    sample_rows: list[dict] = field(default_factory=list)
    raw_llm_output: str = ""

    def to_dict(self) -> dict:
        return {
            "output_name": self.output_name,
            "luid": self.luid,
            "ds_description": self.ds_description,
            "column_descriptions": dict(self.column_descriptions),
            "columns": list(self.columns),
            "sample_rows": list(self.sample_rows),
        }


# === LLM I/O =========================================================

def _ssl_ctx() -> Optional[ssl.SSLContext]:
    try:
        return ssl.create_default_context() if GATEWAY_VERIFY_SSL else ssl._create_unverified_context()
    except Exception:
        return None


def _llm_chat(user_msg: str, max_retries: int = 3) -> str:
    if not GATEWAY_KEY or not GATEWAY_URL or "your-gateway.example.com" in GATEWAY_URL:
        raise RuntimeError(
            "LLM gateway not configured. Set LLM_GATEWAY_URL/KEY/MODEL env vars "
            "or run `python3 -m skill.scripts.llm_config`."
        )
    payload = {
        "model": GATEWAY_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ],
        "stream": False,
    }
    body = json.dumps(payload).encode("utf-8")
    ctx = _ssl_ctx()
    attempt = 0
    while True:
        req = urlrequest.Request(GATEWAY_URL, data=body, method="POST")
        req.add_header("Authorization", f"Bearer {GATEWAY_KEY}")
        req.add_header("Content-Type", "application/json")
        try:
            with urlrequest.urlopen(req, timeout=120, context=ctx) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                choices = data.get("choices") or []
                if not choices:
                    raise RuntimeError(f"no choices in gateway response: {str(data)[:200]}")
                return (choices[0].get("message") or {}).get("content") or ""
        except (error.HTTPError, error.URLError, TimeoutError) as e:
            if attempt < max_retries:
                attempt += 1
                time.sleep(2 ** attempt)
                continue
            raise RuntimeError(f"gateway call failed after {max_retries} retries: {e}")


def _strip_fence(s: str) -> str:
    s = s.strip()
    if s.startswith("```"):
        s = re.sub(r"^```[a-zA-Z]*\s*", "", s)
        if s.endswith("```"):
            s = s[: -3]
    return s.strip()


def _parse_json(raw: str) -> dict:
    s = _strip_fence(raw)
    m = re.search(r"\{.*\}", s, flags=re.DOTALL)
    if m:
        s = m.group(0)
    return json.loads(s)


def _coerce_sample(rows: list, max_rows: int = 5) -> list[dict]:
    """Trim sample to <=5 rows + redact obvious PII heuristically."""
    out = []
    for r in (rows or [])[:max_rows]:
        if isinstance(r, dict):
            out.append({k: ("..." if isinstance(v, str) and len(v) > 80 else v)
                        for k, v in r.items()})
    return out


def _safe_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.\-]+", "_", (name or "out"))


# === Public: generate ===============================================

def generate_descriptions(spec: Spec, output_name: str,
                          columns: list[str],
                          sample_rows: Optional[list[dict]] = None,
                          luid: str = "") -> DescriptionProposal:
    """LLM call to produce DS + per-column descriptions for one output.
    Does NOT touch the server. Returns the proposal so the caller can
    inspect, write to disk, then optionally apply."""
    out: Optional[Output] = next(
        (o for o in spec.outputs if o.name == output_name), None)
    if out is None:
        raise ValueError(f"output {output_name!r} not found on spec")

    user_blob = json.dumps({
        "flow_intent": spec.request,
        "output_name": output_name,
        "output_kind": out.kind,
        "output_intent": out.description or "",
        "columns": list(columns),
        "sample_rows": _coerce_sample(sample_rows or []),
    }, indent=2)

    raw = _llm_chat(user_blob)
    parsed = _parse_json(raw)

    col_desc: dict[str, str] = {}
    for c in (parsed.get("columns") or []):
        n = c.get("name")
        d = c.get("description") or ""
        if n and isinstance(n, str) and isinstance(d, str):
            col_desc[n] = d.strip()

    return DescriptionProposal(
        output_name=output_name,
        luid=luid,
        ds_description=(parsed.get("ds_description") or "").strip(),
        column_descriptions=col_desc,
        columns=list(columns),
        sample_rows=_coerce_sample(sample_rows or []),
        raw_llm_output=raw,
    )


# === Public: apply ==================================================

# Pandas / Hyper -> Tableau .tds datatype mapping. The .tds XML schema
# uses these names: integer, real, string, date, datetime, boolean.
# We don't need the full set - just enough for the most common output
# columns. Anything not on this map defaults to 'string'.
_DECL_TO_TDS_TYPE = {
    "int": "integer", "integer": "integer",
    "decimal": "real", "real": "real", "float": "real", "double": "real",
    "string": "string", "str": "string",
    "date": "date",
    "datetime": "datetime", "timestamp": "datetime",
    "bool": "boolean", "boolean": "boolean",
}


def _signin():
    from tflb_lib import publishing
    cfg = publishing.config_from_env()
    return publishing.sign_in(cfg)


def _apply_ds_description(server, luid: str, description: str) -> dict:
    """Update DS-level description via TSC's REST surface."""
    try:
        item = server.datasources.get_by_id(luid)
        item.description = description
        server.datasources.update(item)
        return {"status": "ok"}
    except Exception as e:
        return {"status": "error", "type": type(e).__name__, "message": str(e)}


def _apply_column_descriptions_via_tds(
    server, luid: str, descriptions: dict[str, str],
    column_types: Optional[dict[str, str]] = None,
    work_dir: Optional[Path] = None,
) -> dict:
    """Apply per-column descriptions by .tds round-trip.

    Steps:
      1. `server.datasources.download(luid, include_extract=True)` -> .tdsx.
      2. Unzip to a working directory; locate the single .tds and the
         Data/Extracts/*.hyper sidecar.
      3. Parse the .tds XML; for each field in `descriptions`, find the
         existing `<column name='[X]' ...>` element OR create a new one
         (with the inferred datatype/role/type), then replace any
         existing `<desc>` child with a fresh
         `<desc><formatted-text><run>...</run></formatted-text></desc>`.
      4. Repack the .tdsx (.tds + Data/Extracts/*.hyper).
      5. `server.datasources.publish(item, path, mode='Overwrite')`.
         The LUID is preserved across the overwrite.

    `column_types` is an optional `{column_name: declared_type_name}`
    map - declared names match the spec's lowercased shorthand
    (`int`/`decimal`/`string`/`bool`/`date`/`datetime`). When missing
    or unknown, the column lands as `string` / `dimension`.
    """
    import shutil
    import tempfile
    import zipfile
    import xml.etree.ElementTree as ET
    import tableauserverclient as TSC  # noqa: F401 (import here to keep top-level import light)

    if not descriptions:
        return {"status": "skipped", "reason": "no column descriptions to apply"}

    work_dir = Path(work_dir) if work_dir else Path(tempfile.mkdtemp(prefix="tpa_md_"))
    work_dir.mkdir(parents=True, exist_ok=True)
    # Clean prior contents to avoid stale .tds / hyper from a previous attempt
    for p in work_dir.iterdir() if work_dir.exists() else []:
        if p.is_file():
            p.unlink()
        elif p.is_dir():
            shutil.rmtree(p)

    try:
        # Step 1: download
        tdsx_path = server.datasources.download(
            luid, filepath=str(work_dir), include_extract=True
        )
        tdsx_path = Path(tdsx_path)

        # Step 2: unzip
        with zipfile.ZipFile(tdsx_path) as zf:
            zf.extractall(work_dir)
        tds_files = list(work_dir.glob("*.tds"))
        if not tds_files:
            return {"status": "error", "reason": "no .tds inside downloaded .tdsx"}
        tds_path = tds_files[0]
        hyper_files = list((work_dir / "Data" / "Extracts").glob("*.hyper")) if (work_dir / "Data" / "Extracts").exists() else []

        # Step 3: inject descriptions
        tree = ET.parse(tds_path)
        root = tree.getroot()
        existing = {c.get("name"): c for c in root.findall("./column")}
        types = column_types or {}
        added = 0
        updated = 0
        for col, desc in descriptions.items():
            if not col or not desc:
                continue
            name_attr = f"[{col}]"
            decl = (types.get(col) or "string").lower()
            tds_dt = _DECL_TO_TDS_TYPE.get(decl, "string")
            is_measure = tds_dt in ("integer", "real")
            if name_attr in existing:
                col_elem = existing[name_attr]
                old_desc = col_elem.find("desc")
                if old_desc is not None:
                    col_elem.remove(old_desc)
                updated += 1
            else:
                col_elem = ET.SubElement(root, "column")
                col_elem.set("caption", col)
                col_elem.set("datatype", tds_dt)
                col_elem.set("name", name_attr)
                col_elem.set("role", "measure" if is_measure else "dimension")
                col_elem.set("type", "quantitative" if is_measure else "nominal")
                added += 1
            d = ET.SubElement(col_elem, "desc")
            ft = ET.SubElement(d, "formatted-text")
            run = ET.SubElement(ft, "run")
            run.text = desc
        ET.indent(tree, space="  ")
        tree.write(tds_path, encoding="utf-8", xml_declaration=True)

        # Step 4: repack
        new_tdsx = work_dir / f"{tds_path.stem}.tdsx"
        with zipfile.ZipFile(new_tdsx, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.write(tds_path, tds_path.name)
            for hp in hyper_files:
                zf.write(hp, f"Data/Extracts/{hp.name}")

        # Step 5: republish (Overwrite). Need the existing item's
        # project_id + name for the publish call.
        existing_item = server.datasources.get_by_id(luid)
        ds_item = type(existing_item)(
            project_id=existing_item.project_id,
            name=existing_item.name,
        )
        # Preserve DS description if one was set in step (1) on this run.
        if existing_item.description:
            ds_item.description = existing_item.description
        pub = server.datasources.publish(ds_item, str(new_tdsx), mode="Overwrite")
        return {
            "status": "ok",
            "added_column_elements": added,
            "updated_column_elements": updated,
            "luid": pub.id,
        }
    except Exception as e:
        return {"status": "error", "type": type(e).__name__, "message": str(e)}


def apply_descriptions(proposal: DescriptionProposal,
                       column_types: Optional[dict[str, str]] = None) -> dict:
    """Apply a generated proposal to the site. DS-level description goes
    first via the REST surface (`datasources.update`); column descriptions
    go via the .tds round-trip path because Cloud's Metadata API has no
    write mutations.

    `column_types` is an optional {col: declared_type} map used when the
    .tds doesn't already have a `<column>` element for that name (we
    have to create one, and Tableau wants the datatype declared)."""
    if not proposal.luid:
        return {"status": "skipped", "reason": "no luid - not yet published"}

    server = _signin()
    try:
        ds_res = (
            _apply_ds_description(server, proposal.luid, proposal.ds_description)
            if proposal.ds_description
            else {"status": "skipped", "reason": "empty ds_description"}
        )
        col_res = _apply_column_descriptions_via_tds(
            server, proposal.luid, proposal.column_descriptions,
            column_types=column_types,
        )
    finally:
        try:
            server.auth.sign_out()
        except Exception:
            pass

    overall = "ok" if (
        ds_res.get("status") in ("ok", "skipped")
        and col_res.get("status") in ("ok", "skipped")
    ) else "partial"
    return {
        "status": overall,
        "ds": ds_res,
        "columns": col_res,
    }


# === Public: orchestrator entry point ===============================

def write_for_output(spec: Spec, output_name: str, luid: str,
                     columns: list[str],
                     sample_rows: Optional[list[dict]],
                     run_dir: Path,
                     review: bool = False,
                     column_types: Optional[dict[str, str]] = None) -> dict:
    """One-shot: generate proposal, save audit JSON, optionally apply.

    `review=True` -> stop after saving the proposal so the user can
    inspect via AskUserQuestion.

    `column_types` is an optional {col: declared_type} map (e.g.
    `{"acres_per_day": "decimal", "is_active": "bool"}`) used by the
    .tds-roundtrip path to assign correct datatype/role to columns
    that aren't already declared in the published DS's .tds.
    """
    run_dir = Path(run_dir).resolve()
    run_dir.mkdir(parents=True, exist_ok=True)

    proposal = generate_descriptions(spec, output_name, columns,
                                     sample_rows=sample_rows, luid=luid)

    audit_path = run_dir / f"metadata_{_safe_name(output_name)}.json"
    audit_path.write_text(json.dumps(proposal.to_dict(), indent=2))

    if review:
        return {
            "status": "needs_user_decision",
            "output_name": output_name,
            "luid": luid,
            "proposal_path": str(audit_path),
            "ds_description": proposal.ds_description,
            "column_count": len(proposal.column_descriptions),
        }

    apply_result = apply_descriptions(proposal, column_types=column_types)
    return {
        "status": apply_result.get("status", "unknown"),
        "output_name": output_name,
        "luid": luid,
        "proposal_path": str(audit_path),
        "applied": apply_result,
    }


def main(argv: Optional[list[str]] = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(
        description="Phase 11 metadata writer: generate + apply DS / column descriptions.")
    ap.add_argument("--spec", required=True, help="Path to spec.json")
    ap.add_argument("--output-name", required=True,
                    help="Which spec.outputs[*].name to operate on")
    ap.add_argument("--luid", default="",
                    help="LUID of the published DS on the site")
    ap.add_argument("--columns", required=True,
                    help="Comma-separated list of column names")
    ap.add_argument("--sample-rows", default="",
                    help="Path to a JSON file with a list of sample rows")
    ap.add_argument("--run-dir", required=True,
                    help="Where to save the audit JSON")
    ap.add_argument("--review", action="store_true",
                    help="Stop after generating proposal; do not apply")
    args = ap.parse_args(argv)

    from skill.scripts.publish import _load_spec
    spec = _load_spec(Path(args.spec))
    columns = [c.strip() for c in args.columns.split(",") if c.strip()]
    sample = []
    if args.sample_rows:
        sample = json.loads(Path(args.sample_rows).read_text())

    result = write_for_output(spec, args.output_name, args.luid,
                              columns, sample, Path(args.run_dir),
                              review=args.review)
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
