"""
Tableau Prep Script: REST/GraphQL API caller.

Generated by tableau-prep-etl skill from templates/api_caller.py.j2.

URL: http://data.gdeltproject.org/events/index.html
Auth: none
Format hint: csv_index_then_zip
GraphQL: False

Format dispatch:
  - json (default)            : JSON-decode the response, drill envelope keys
  - csv                       : pd.read_csv() on the response body
  - csv_index_then_zip        : parse HTML directory listing for the latest
                                .CSV.zip, fetch + unzip + read CSV
                                (used by GDELT-style sources)
  - jsonl / ndjson            : line-delimited JSON
"""
import csv
import io
import json
import os
import re
import ssl
import time
import zipfile
from urllib import error, request as urlrequest
from urllib.parse import urljoin, urlparse

import pandas as pd

API_URL = "http://data.gdeltproject.org/events/index.html"
FORMAT = "csv_index_then_zip"

GRAPHQL = False


VERIFY_SSL = True
TIMEOUT_S = 120
MAX_RETRIES = 3
COUNTRY_FILTER = "US"

INDEX_LINK_PATTERN = "href=\"([^\"]+\\.CSV\\.zip)\""


def _ssl_ctx():
    try:
        return ssl.create_default_context() if VERIFY_SSL else ssl._create_unverified_context()
    except Exception:
        return None


def _build_headers():
    headers = {"Content-Type": "application/json"}
    
    return headers


def _http_get_bytes(url: str) -> bytes:
    headers = _build_headers()
    ctx = _ssl_ctx()
    attempt = 0
    while True:
        req = urlrequest.Request(url, method="GET")
        for k, v in headers.items():
            req.add_header(k, v)
        try:
            with urlrequest.urlopen(req, timeout=TIMEOUT_S, context=ctx) as resp:
                return resp.read()
        except (error.HTTPError, error.URLError, TimeoutError):
            if attempt < MAX_RETRIES:
                attempt += 1
                time.sleep(2 ** attempt)
                continue
            raise


def _http_request_json(payload=None, method="GET"):
    body = json.dumps(payload).encode("utf-8") if payload else None
    headers = _build_headers()
    ctx = _ssl_ctx()
    attempt = 0
    while True:
        req = urlrequest.Request(API_URL, data=body, method=method)
        for k, v in headers.items():
            req.add_header(k, v)
        try:
            with urlrequest.urlopen(req, timeout=TIMEOUT_S, context=ctx) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except (error.HTTPError, error.URLError, TimeoutError):
            if attempt < MAX_RETRIES:
                attempt += 1
                time.sleep(2 ** attempt)
                continue
            raise


def _df_from_csv_bytes(b: bytes, has_header: bool = True) -> pd.DataFrame:
    text = b.decode("utf-8", errors="replace")
    if has_header:
        return pd.read_csv(io.StringIO(text))
    # GDELT events don't ship a header; use the v1 column list
    GDELT_V1_COLS = [
        "GLOBALEVENTID", "SQLDATE", "MonthYear", "Year", "FractionDate",
        "Actor1Code", "Actor1Name", "Actor1CountryCode", "Actor1KnownGroupCode",
        "Actor1EthnicCode", "Actor1Religion1Code", "Actor1Religion2Code",
        "Actor1Type1Code", "Actor1Type2Code", "Actor1Type3Code",
        "Actor2Code", "Actor2Name", "Actor2CountryCode", "Actor2KnownGroupCode",
        "Actor2EthnicCode", "Actor2Religion1Code", "Actor2Religion2Code",
        "Actor2Type1Code", "Actor2Type2Code", "Actor2Type3Code",
        "IsRootEvent", "EventCode", "EventBaseCode", "EventRootCode",
        "QuadClass", "GoldsteinScale", "NumMentions", "NumSources",
        "NumArticles", "AvgTone", "Actor1Geo_Type", "Actor1Geo_FullName",
        "Actor1Geo_CountryCode", "Actor1Geo_ADM1Code", "Actor1Geo_Lat",
        "Actor1Geo_Long", "Actor1Geo_FeatureID",
        "Actor2Geo_Type", "Actor2Geo_FullName", "Actor2Geo_CountryCode",
        "Actor2Geo_ADM1Code", "Actor2Geo_Lat", "Actor2Geo_Long", "Actor2Geo_FeatureID",
        "ActionGeo_Type", "ActionGeo_FullName", "ActionGeo_CountryCode",
        "ActionGeo_ADM1Code", "ActionGeo_Lat", "ActionGeo_Long", "ActionGeo_FeatureID",
        "DATEADDED", "SOURCEURL",
    ]
    return pd.read_csv(io.StringIO(text), sep="\t", header=None, names=GDELT_V1_COLS,
                       low_memory=False)


def _fetch_csv_index_then_zip() -> pd.DataFrame:
    """Format: csv_index_then_zip.
    Read API_URL as an HTML directory listing, find the latest .CSV.zip
    link, fetch + unzip + read the CSV. Tailored to GDELT events index."""
    index_html = _http_get_bytes(API_URL).decode("utf-8", errors="replace")
    matches = re.findall(INDEX_LINK_PATTERN, index_html)
    if not matches:
        raise RuntimeError(f"no .CSV.zip links matched at {API_URL}")
    # Pick the most recent (lexicographic max for date-prefixed filenames)
    latest = sorted(matches)[-1]
    # Resolve relative to the index URL's directory
    base = API_URL.rsplit("/", 1)[0] + "/"
    zip_url = urljoin(base, latest)
    zip_bytes = _http_get_bytes(zip_url)
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
        csv_names = [n for n in zf.namelist() if n.lower().endswith(".csv")]
        if not csv_names:
            raise RuntimeError(f"no CSV inside {zip_url}")
        with zf.open(csv_names[0]) as fp:
            csv_bytes = fp.read()
    df = _df_from_csv_bytes(csv_bytes, has_header=False)
    if COUNTRY_FILTER and "ActionGeo_CountryCode" in df.columns:
        df = df[df["ActionGeo_CountryCode"] == COUNTRY_FILTER].reset_index(drop=True)
    return df


def _fetch_csv() -> pd.DataFrame:
    return _df_from_csv_bytes(_http_get_bytes(API_URL), has_header=True)


def _fetch_jsonl() -> pd.DataFrame:
    body = _http_get_bytes(API_URL).decode("utf-8", errors="replace")
    rows = [json.loads(ln) for ln in body.splitlines() if ln.strip()]
    return pd.DataFrame(rows)


def _fetch_json() -> pd.DataFrame:
    if GRAPHQL:
        data = _http_request_json({"query": GRAPHQL_QUERY}, method="POST")
        rows = data.get("data") or data
    else:
        rows = _http_request_json(method="GET")
    if isinstance(rows, dict):
        for key in ("results", "data", "items", "records", "rows"):
            if key in rows and isinstance(rows[key], list):
                rows = rows[key]
                break
    if isinstance(rows, list):
        return pd.DataFrame(rows)
    return pd.DataFrame([{"raw": json.dumps(rows)}])


_DISPATCH = {
    "json": _fetch_json,
    "csv": _fetch_csv,
    "csv_index_then_zip": _fetch_csv_index_then_zip,
    "jsonl": _fetch_jsonl,
    "ndjson": _fetch_jsonl,
}


def call_api(df):
    """Tableau Prep entry point. Input df is a trigger row (single 'folder'-like
    column from the rewired local xlsx). We ignore it and pull from the API.
    Output: a DataFrame matching the API's records, schema-inferred."""
    fetcher = _DISPATCH.get(FORMAT, _fetch_json)
    return fetcher()


def get_output_schema():
    # Schema is best-effort. The skill's run_loop verifies the actual columns
    # match what call_api returned, and asks for a refinement if not.
    return pd.DataFrame({
        "id": prep_string(),  # noqa: F821
    })