"""
Tableau Prep Script: REST/GraphQL API caller.

Generated by tableau-prep-etl skill from templates/api_caller.py.j2.

URL: https://services1.arcgis.com/Hp6G80Pky0om7QvQ/arcgis/rest/services/Electric_Power_Transmission_Lines/FeatureServer/0/query
Auth: none
Format hint: arcgis_features
GraphQL: False

Format dispatch:
  - json (default)            : JSON-decode the response, drill envelope keys
  - csv                       : pd.read_csv() on the response body
  - csv_index_then_zip        : parse HTML directory listing for the latest
                                .CSV.zip, fetch + unzip + read CSV
                                (used by GDELT-style sources)
  - jsonl / ndjson            : line-delimited JSON
  - arcgis_features           : ArcGIS REST FeatureServer/MapServer query
                                endpoint. Walks resultOffset pagination,
                                flattens 'attributes' (+ optional point
                                geometry) into rows.
"""
import csv
import io
import json
import os
import re
import ssl
import time
import zipfile
from urllib import error, request as urlrequest
from urllib.parse import urljoin, urlparse

import pandas as pd

API_URL = "https://services1.arcgis.com/Hp6G80Pky0om7QvQ/arcgis/rest/services/Electric_Power_Transmission_Lines/FeatureServer/0/query"
FORMAT = "arcgis_features"

GRAPHQL = False


VERIFY_SSL = True
TIMEOUT_S = 180
MAX_RETRIES = 3
COUNTRY_FILTER = ""

INDEX_LINK_PATTERN = r'href="([^"]+\.CSV\.zip)"'

# ArcGIS-specific knobs (ignored when format != 'arcgis_features')
ARCGIS_WHERE = "VOLTAGE \u003e= 345 AND SUB_1 IS NOT NULL AND SUB_2 IS NOT NULL AND SUB_1 \u003c\u003e \u0027NOT AVAILABLE\u0027 AND SUB_2 \u003c\u003e \u0027NOT AVAILABLE\u0027"
ARCGIS_OUT_FIELDS = "OBJECTID,ID,SUB_1,SUB_2,VOLTAGE,VOLT_CLASS,OWNER,STATUS"
ARCGIS_PAGE_SIZE = 1000
ARCGIS_MAX_RECORDS = 0  # 0 = no cap
ARCGIS_RETURN_GEOMETRY = True
ARCGIS_OUT_SR = 4326  # 4326 = WGS84 lat/lon
# 'point' (default) or 'polyline'. Polyline mode flattens first/last
# vertex of the first path into start_lon/start_lat/end_lon/end_lat —
# the canonical edge-table shape for graph analytics on transmission
# lines, road networks, etc.
ARCGIS_GEOMETRY_KIND = "polyline"

# CSV-specific knobs (ignored when format != 'csv').
# CSV_ENCODING: e.g. 'utf-8' or 'latin-1'. Some open-data publishers
#   ship Latin-1 CSVs that mojibake-decode under utf-8.
# CSV_RENAME_MAP: rename columns post-read so downstream nodes see clean,
#   join-friendly names (esp. when source uses bilingual `English:French`
#   headers — Maestro accepts them but they're awkward to reference).
# CSV_SCHEMA: explicit {column: prep_type} for get_output_schema(). Required
#   when generate_flow needs to wire joins on specific columns; otherwise
#   stub schema causes "Unable to retrieve results for field" downstream.
# CSV_USECOLS: optional list of source columns to keep (post-rename if
#   present in CSV_RENAME_MAP). Trims wide CSVs.
CSV_ENCODING = "utf-8"
CSV_RENAME_MAP = {}
CSV_SCHEMA = {}
CSV_USECOLS = []


def _ssl_ctx():
    try:
        if not VERIFY_SSL:
            return ssl._create_unverified_context()
        # macOS Python.org distros often lack a system CA bundle; prefer
        # certifi's bundle when available so HTTPS to public APIs works
        # out-of-the-box under TabPy without requiring the user to run
        # /Applications/Python*/Install\ Certificates.command first.
        try:
            import certifi
            return ssl.create_default_context(cafile=certifi.where())
        except ImportError:
            return ssl.create_default_context()
    except Exception:
        return None


def _build_headers():
    headers = {"Content-Type": "application/json"}
    
    return headers


def _http_get_bytes(url: str) -> bytes:
    headers = _build_headers()
    ctx = _ssl_ctx()
    attempt = 0
    while True:
        req = urlrequest.Request(url, method="GET")
        for k, v in headers.items():
            req.add_header(k, v)
        try:
            with urlrequest.urlopen(req, timeout=TIMEOUT_S, context=ctx) as resp:
                return resp.read()
        except (error.HTTPError, error.URLError, TimeoutError):
            if attempt < MAX_RETRIES:
                attempt += 1
                time.sleep(2 ** attempt)
                continue
            raise


def _http_request_json(payload=None, method="GET"):
    body = json.dumps(payload).encode("utf-8") if payload else None
    headers = _build_headers()
    ctx = _ssl_ctx()
    attempt = 0
    while True:
        req = urlrequest.Request(API_URL, data=body, method=method)
        for k, v in headers.items():
            req.add_header(k, v)
        try:
            with urlrequest.urlopen(req, timeout=TIMEOUT_S, context=ctx) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except (error.HTTPError, error.URLError, TimeoutError):
            if attempt < MAX_RETRIES:
                attempt += 1
                time.sleep(2 ** attempt)
                continue
            raise


def _df_from_csv_bytes(b: bytes, has_header: bool = True) -> pd.DataFrame:
    # GDELT (csv_index_then_zip) is always UTF-8; OTF concordance files are
    # Latin-1. Honor CSV_ENCODING for the headered-CSV path.
    encoding = CSV_ENCODING if has_header else "utf-8"
    text = b.decode(encoding, errors="replace")
    if has_header:
        df = pd.read_csv(io.StringIO(text))
        if CSV_RENAME_MAP:
            df = df.rename(columns=CSV_RENAME_MAP)
        if CSV_USECOLS:
            keep = [c for c in CSV_USECOLS if c in df.columns]
            df = df[keep]
        return df
    # GDELT events don't ship a header; use the v1 column list
    GDELT_V1_COLS = [
        "GLOBALEVENTID", "SQLDATE", "MonthYear", "Year", "FractionDate",
        "Actor1Code", "Actor1Name", "Actor1CountryCode", "Actor1KnownGroupCode",
        "Actor1EthnicCode", "Actor1Religion1Code", "Actor1Religion2Code",
        "Actor1Type1Code", "Actor1Type2Code", "Actor1Type3Code",
        "Actor2Code", "Actor2Name", "Actor2CountryCode", "Actor2KnownGroupCode",
        "Actor2EthnicCode", "Actor2Religion1Code", "Actor2Religion2Code",
        "Actor2Type1Code", "Actor2Type2Code", "Actor2Type3Code",
        "IsRootEvent", "EventCode", "EventBaseCode", "EventRootCode",
        "QuadClass", "GoldsteinScale", "NumMentions", "NumSources",
        "NumArticles", "AvgTone", "Actor1Geo_Type", "Actor1Geo_FullName",
        "Actor1Geo_CountryCode", "Actor1Geo_ADM1Code", "Actor1Geo_Lat",
        "Actor1Geo_Long", "Actor1Geo_FeatureID",
        "Actor2Geo_Type", "Actor2Geo_FullName", "Actor2Geo_CountryCode",
        "Actor2Geo_ADM1Code", "Actor2Geo_Lat", "Actor2Geo_Long", "Actor2Geo_FeatureID",
        "ActionGeo_Type", "ActionGeo_FullName", "ActionGeo_CountryCode",
        "ActionGeo_ADM1Code", "ActionGeo_Lat", "ActionGeo_Long", "ActionGeo_FeatureID",
        "DATEADDED", "SOURCEURL",
    ]
    return pd.read_csv(io.StringIO(text), sep="\t", header=None, names=GDELT_V1_COLS,
                       low_memory=False)


def _fetch_csv_index_then_zip() -> pd.DataFrame:
    """Format: csv_index_then_zip.
    Read API_URL as an HTML directory listing, find the latest .CSV.zip
    link, fetch + unzip + read the CSV. Tailored to GDELT events index."""
    index_html = _http_get_bytes(API_URL).decode("utf-8", errors="replace")
    matches = re.findall(INDEX_LINK_PATTERN, index_html, flags=re.IGNORECASE)
    if not matches:
        raise RuntimeError(f"no .CSV.zip links matched at {API_URL}")
    # Pick the most recent (lexicographic max for date-prefixed filenames)
    latest = sorted(matches)[-1]
    # Resolve relative to the index URL's directory
    base = API_URL.rsplit("/", 1)[0] + "/"
    zip_url = urljoin(base, latest)
    zip_bytes = _http_get_bytes(zip_url)
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
        csv_names = [n for n in zf.namelist() if n.lower().endswith(".csv")]
        if not csv_names:
            raise RuntimeError(f"no CSV inside {zip_url}")
        with zf.open(csv_names[0]) as fp:
            csv_bytes = fp.read()
    df = _df_from_csv_bytes(csv_bytes, has_header=False)
    if COUNTRY_FILTER and "ActionGeo_CountryCode" in df.columns:
        df = df[df["ActionGeo_CountryCode"] == COUNTRY_FILTER].reset_index(drop=True)
    return df


def _fetch_csv() -> pd.DataFrame:
    return _df_from_csv_bytes(_http_get_bytes(API_URL), has_header=True)


def _fetch_jsonl() -> pd.DataFrame:
    body = _http_get_bytes(API_URL).decode("utf-8", errors="replace")
    rows = [json.loads(ln) for ln in body.splitlines() if ln.strip()]
    return pd.DataFrame(rows)


def _fetch_json() -> pd.DataFrame:
    if GRAPHQL:
        data = _http_request_json({"query": GRAPHQL_QUERY}, method="POST")
        rows = data.get("data") or data
    else:
        rows = _http_request_json(method="GET")
    if isinstance(rows, dict):
        for key in ("results", "data", "items", "records", "rows"):
            if key in rows and isinstance(rows[key], list):
                rows = rows[key]
                break
    if isinstance(rows, list):
        return pd.DataFrame(rows)
    return pd.DataFrame([{"raw": json.dumps(rows)}])


def _fetch_arcgis_features() -> pd.DataFrame:
    """Format: arcgis_features.
    Query an ArcGIS REST FeatureServer/MapServer layer's /query endpoint,
    walk resultOffset pagination, flatten attributes + point geometry."""
    from urllib.parse import urlencode

    base = API_URL.rstrip("/")
    if not base.endswith("/query"):
        base = base + "/query"

    rows: list[dict] = []
    offset = 0
    while True:
        params = {
            "where": ARCGIS_WHERE,
            "outFields": ARCGIS_OUT_FIELDS,
            "f": "json",
            "returnGeometry": "true" if ARCGIS_RETURN_GEOMETRY else "false",
            "outSR": str(ARCGIS_OUT_SR),
            "resultOffset": str(offset),
            "resultRecordCount": str(ARCGIS_PAGE_SIZE),
        }
        url = base + "?" + urlencode(params)
        body = _http_get_bytes(url)
        data = json.loads(body.decode("utf-8", errors="replace"))
        if "error" in data:
            raise RuntimeError(f"ArcGIS error: {data['error']}")
        feats = data.get("features") or []
        if not feats:
            break
        for f in feats:
            attrs = dict(f.get("attributes") or {})
            geom = f.get("geometry") or {}
            # Point geometry: flatten x/y to lon/lat
            if "x" in geom and "y" in geom:
                attrs.setdefault("longitude", geom.get("x"))
                attrs.setdefault("latitude", geom.get("y"))
            # Polyline geometry: extract first and last vertex of the
            # first path as start/end endpoints. Sufficient for graph
            # edge tables where each line connects two stations.
            elif "paths" in geom and geom["paths"]:
                first_path = geom["paths"][0]
                if first_path:
                    sx, sy = first_path[0][0], first_path[0][1]
                    ex, ey = first_path[-1][0], first_path[-1][1]
                    attrs.setdefault("start_lon", sx)
                    attrs.setdefault("start_lat", sy)
                    attrs.setdefault("end_lon", ex)
                    attrs.setdefault("end_lat", ey)
            elif geom:
                attrs.setdefault("geometry_json", json.dumps(geom))
            rows.append(attrs)
        if ARCGIS_MAX_RECORDS and len(rows) >= ARCGIS_MAX_RECORDS:
            rows = rows[:ARCGIS_MAX_RECORDS]
            break
        # ArcGIS sets exceededTransferLimit when more pages remain
        if not data.get("exceededTransferLimit") and len(feats) < ARCGIS_PAGE_SIZE:
            break
        offset += len(feats)

    df = pd.DataFrame(rows)
    # ArcGIS epoch-millis timestamp fields → ISO 8601 strings.
    # We emit strings (not pd.Timestamp) because TabPy serializes the
    # response via json.dumps which can't handle Timestamp objects;
    # Tableau Prep happily parses the ISO strings as datetimes downstream.
    for col in df.columns:
        if col.lower().endswith(("date", "datetime", "time")) and df[col].dtype != object:
            try:
                ts = pd.to_datetime(df[col], unit="ms", errors="coerce", utc=True)
                df[col] = ts.dt.strftime("%Y-%m-%dT%H:%M:%SZ").where(ts.notna(), None)
            except Exception:
                pass
    return df


_DISPATCH = {
    "json": _fetch_json,
    "csv": _fetch_csv,
    "csv_index_then_zip": _fetch_csv_index_then_zip,
    "jsonl": _fetch_jsonl,
    "ndjson": _fetch_jsonl,
    "arcgis_features": _fetch_arcgis_features,
}


def call_api(df):
    """Tableau Prep entry point. Input df is a trigger row (single 'folder'-like
    column from the rewired local xlsx). We ignore it and pull from the API.
    Output: a DataFrame matching the API's records, schema-inferred."""
    fetcher = _DISPATCH.get(FORMAT, _fetch_json)
    return fetcher()


_GDELT_V1_DECIMAL = {
    "FractionDate", "GoldsteinScale", "AvgTone",
    "Actor1Geo_Lat", "Actor1Geo_Long",
    "Actor2Geo_Lat", "Actor2Geo_Long",
    "ActionGeo_Lat", "ActionGeo_Long",
}
_GDELT_V1_INT = {
    "GLOBALEVENTID", "SQLDATE", "MonthYear", "Year", "IsRootEvent",
    "EventCode", "EventBaseCode", "EventRootCode", "QuadClass",
    "NumMentions", "NumSources", "NumArticles", "DATEADDED",
    "Actor1Geo_Type", "Actor2Geo_Type", "ActionGeo_Type",
}


def _gdelt_v1_schema():
    GDELT_V1_COLS = [
        "GLOBALEVENTID", "SQLDATE", "MonthYear", "Year", "FractionDate",
        "Actor1Code", "Actor1Name", "Actor1CountryCode", "Actor1KnownGroupCode",
        "Actor1EthnicCode", "Actor1Religion1Code", "Actor1Religion2Code",
        "Actor1Type1Code", "Actor1Type2Code", "Actor1Type3Code",
        "Actor2Code", "Actor2Name", "Actor2CountryCode", "Actor2KnownGroupCode",
        "Actor2EthnicCode", "Actor2Religion1Code", "Actor2Religion2Code",
        "Actor2Type1Code", "Actor2Type2Code", "Actor2Type3Code",
        "IsRootEvent", "EventCode", "EventBaseCode", "EventRootCode",
        "QuadClass", "GoldsteinScale", "NumMentions", "NumSources",
        "NumArticles", "AvgTone", "Actor1Geo_Type", "Actor1Geo_FullName",
        "Actor1Geo_CountryCode", "Actor1Geo_ADM1Code", "Actor1Geo_Lat",
        "Actor1Geo_Long", "Actor1Geo_FeatureID",
        "Actor2Geo_Type", "Actor2Geo_FullName", "Actor2Geo_CountryCode",
        "Actor2Geo_ADM1Code", "Actor2Geo_Lat", "Actor2Geo_Long", "Actor2Geo_FeatureID",
        "ActionGeo_Type", "ActionGeo_FullName", "ActionGeo_CountryCode",
        "ActionGeo_ADM1Code", "ActionGeo_Lat", "ActionGeo_Long", "ActionGeo_FeatureID",
        "DATEADDED", "SOURCEURL",
    ]
    schema = {}
    for c in GDELT_V1_COLS:
        if c in _GDELT_V1_INT:
            schema[c] = prep_int()  # noqa: F821
        elif c in _GDELT_V1_DECIMAL:
            schema[c] = prep_decimal()  # noqa: F821
        else:
            schema[c] = prep_string()  # noqa: F821
    return schema


def get_output_schema():
    # Schema must match what call_api actually returns or Maestro fails with
    # "Unable to retrieve results for field". We derive shape from FORMAT
    # because each fetcher returns a different DataFrame shape.
    if FORMAT == "arcgis_features" and ARCGIS_OUT_FIELDS and ARCGIS_OUT_FIELDS != "*":
        fields = [f.strip() for f in ARCGIS_OUT_FIELDS.split(",") if f.strip()]
        schema = {}
        for f in fields:
            lf = f.lower()
            if lf.endswith(("date", "datetime", "time")):
                schema[f] = prep_string()  # noqa: F821 — emitted as ISO 8601
            elif any(k in lf for k in ("acres", "size", "percent", "lat", "lon")):
                schema[f] = prep_decimal()  # noqa: F821
            elif lf in ("objectid",):
                schema[f] = prep_int()  # noqa: F821
            else:
                schema[f] = prep_string()  # noqa: F821
        if ARCGIS_RETURN_GEOMETRY:
            if ARCGIS_GEOMETRY_KIND == "polyline":
                schema.setdefault("start_lon", prep_decimal())  # noqa: F821
                schema.setdefault("start_lat", prep_decimal())  # noqa: F821
                schema.setdefault("end_lon", prep_decimal())    # noqa: F821
                schema.setdefault("end_lat", prep_decimal())    # noqa: F821
            else:
                schema.setdefault("longitude", prep_decimal())  # noqa: F821
                schema.setdefault("latitude", prep_decimal())   # noqa: F821
        return pd.DataFrame(schema)
    if FORMAT == "csv_index_then_zip":
        return pd.DataFrame(_gdelt_v1_schema())
    if FORMAT == "csv" and CSV_SCHEMA:
        # Map declared types ('string'|'int'|'decimal'|'date') to Prep helpers.
        type_map = {
            "string": prep_string(),  # noqa: F821
            "int": prep_int(),  # noqa: F821
            "decimal": prep_decimal(),  # noqa: F821
            "date": prep_date(),  # noqa: F821
            "datetime": prep_datetime(),  # noqa: F821
            "bool": prep_bool(),  # noqa: F821
        }
        schema = {col: type_map.get(t, prep_string()) for col, t in CSV_SCHEMA.items()}  # noqa: F821
        return pd.DataFrame(schema)
    return pd.DataFrame({"raw": prep_string()})  # noqa: F821